[env]
TERM = "xterm-256color"

[window]
padding.x =10
padding.y = 10

decorations = "none"

opacity = 1
blur = true

option_as_alt = "Both"

[font]
# normal.family = "Mononoki Nerd Font"
normal.family = "JetBrainsMono NFP Thin"
size = 9
